import scrapy
# INSTEAD OF XPATH - 
# from whiskyscraper.items import WhiskyscraperItem
from scrapy.loader import ItemLoader

#THIS IS FOR XPATH
import os
from os.path import dirname


class ConstitutionSpider(scrapy.Spider):
    name = "constitution"
    allowed_domains = ["constitutioncenter.org"]
    start_urls = ["https://constitutioncenter.org/the-constitution/full-text"]

    def parse(self, response):
        #the variable defined in the scrapy shell, for each of those items in all found
        for articles in response.css('article.article_body'):
            try:
               yield {
                    'article': articles.css('article.article_body').get()
               }
            except:
                yield {
                    'article': articles.css('article.article_body').get()
                }
            
            
# css instead of xpath

'''
 # use scrapy loader to load item from autogenerated item in py where defined the schema
                l = ItemLoader(item = GovItem(), selector=products)

                #add the article HTML from <article> div but there is no CLASSNAME for the sections within the article to extract clean data from
                l.add_css('article', 'article.article_body')

                yield l.load_item()

'''